# Generated by Django 4.2.6 on 2023-11-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("registration_no", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150)),
                ("course", models.CharField(max_length=300)),
            ],
        ),
    ]
