# Generated by Django 4.2.6 on 2023-11-04 01:28

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration_no",
            field=models.PositiveIntegerField(
                default=students.models.generate_unique_registration_number, unique=True
            ),
        ),
    ]
